[YDS] TopBar에 들어가는 TopBarButton의 isDisabled 프로퍼티 컨트롤 가능하도록 수정
yourssu/YDS-Android pull request #135
Opened 2022-08-04 07:36 UTC by chlwhdtn03

Topbar클래스에

```kotlin
// 코드 일부분
var startDisabled: Boolean = false
set(value) {
    field = value
    binding.startButton.isDisabled = value    
}

companion object {
    @JvmStatic
    @BindingAdapter("startButtonDisabled")
    fun setStartButtonDisabled(topBar: TopBar, isDisabled: Boolean) {    
        topBar.startDisabled = isDisabled    
    }
}
```

코드를 추가하면서, 

TopbarButton의 isDisabled 프로퍼티를 아래 코드로 컨트롤 할 수 있게 됐습니다.

```xml
app:endLeftButtonDisabled="@{viewModel.endLeftButtonDisabled}"
```

![image-20220804152457522](https://user-images.githubusercontent.com/20380647/182790633-eb9c6425-74ad-4f6d-b6fb-a5ce5e896fcd.png)

YDS Storybook의 Topbar 화면에도, TopbarButton마다 Disabled 옵션을 추가했습니다.

2022-08-04 12:53 UTC, shlee4290 approved these changes

2022-08-04 14:22 UTC, chlwhdtn03 commented
SearchTopbar는 이미 구현이 돼 있길래 SingleTitleTopBar, DoubleTitleTopBar만 건드렸습니다!
SingleTitleTopBar, DoubleTitleTopBar에 둘다 똑같이
### `var firstDisabled: Boolean = false`
### `var secondDisabled: Boolean = false`
### `var thirdDisabled: Boolean = false`
추가했고,

```xml
app:firstButtonDisabled="@{viewModel.firstDisabled}"
app:secondButtonDisabled="@{viewModel.secondDisabled}"
app:thirdButtonDisabled="@{viewModel.thirdDisabled}"
```
위에처럼 
똑같이 StoryBook에도 해놨습니다

2022-08-04 14:24 UTC, chlwhdtn03 commented
여기까지 해서 TopBar, SingleTitleTopBar, DoubleTitleTopBar 총 3개 전부 완료됐습니다 😄

2022-08-04 14:25 UTC, shlee4290 submitted a review, later dismissed
빠르시군여 👍

2022-08-04 14:26 UTC, chlwhdtn03 commented
머지 누르면 되는건가요..!

2022-08-04 15:10 UTC, ByeongsuPark commented on DesignSystem/src/main/java/com/yourssu/design/system/component/TopBar.kt
> +        }
이렇게 할 경우 XML에서
```app:endRightButtonDisabled="@{true}"```와 ```app:endRightDisabled="@{true}"``` 
두 경우 모두 사용할 수 있어서 헷갈릴 수도 있을 것 같네요.
BindingAdapter를 따로 쓰실거라면 프로퍼티 이름과 바인딩 어뎁터 속성이름은 통일시켜주시면 좋을 것 같습니다.
DoubleTitleTopBar나, SingleTitleTopBar 모두 동일합니다.

2022-08-04 15:10 UTC, ByeongsuPark commented on DesignSystem/src/main/java/com/yourssu/design/system/component/DoubleTitleTopBar.kt
> +        fun setThirdText(singleTitleTopBar: DoubleTitleTopBar, value: String) {
:+1: 이걸 아무도 못 찾고 있었네여 ㅋㅋㅋㅋ

2022-08-04 15:10 UTC, ByeongsuPark commented on DesignSystem/src/main/java/com/yourssu/design/system/component/DoubleTitleTopBar.kt
> +        fun setThirdText(singleTitleTopBar: DoubleTitleTopBar, value: String) {
이왕이면 변수 이름도 같이 바꿔주시면 👍 👍입니다

2022-08-04 15:11 UTC, ByeongsuPark commented
그리고 SearchTopBar의 isDisabled는 TopBarButton의 isDisabled가 아니라 SearchTextField의 isDisabled인 것 같은데 확인 부탁드릴게여

2022-08-04 15:12 UTC, ByeongsuPark commented
👍  일단 머지하고 추후 작업은 별도의 PR로 올리셔도 괜찮을 것 같네요 편하신대로 가시져

2022-08-04 15:19 UTC, chlwhdtn03 commented
그러면 SearchTopBar에서는 왼쪽에 있는 뒤로가기 버튼의 isDisabled 프로퍼티를 설정할 수 있게 하면 되는건가요??

2022-08-04 15:20 UTC, chlwhdtn03 commented
머지는 안하고 나머지 사항들도 다 고쳐서 내일 여기에 다시 올리겠습니다!

2022-08-04 15:23 UTC, ByeongsuPark commented
> 그러면 SearchTopBar에서는 왼쪽에 있는 뒤로가기 버튼의 isDisabled 프로퍼티를 설정할 수 있게 하면 되는건가요??

넵:+1:

2022-08-05 02:21 UTC, chlwhdtn03 commented
> > 그러면 SearchTopBar에서는 왼쪽에 있는 뒤로가기 버튼의 isDisabled 프로퍼티를 설정할 수 있게 하면 되는건가요??
> 
> 넵👍

헉 방금 SearchTopBar까지 마무리 하고 푸시 하려 했는데

2022-08-05 02:24 UTC, chlwhdtn03 commented
StoryBook 보니까 SearchTopBar에서는 LeftArrow버튼을 누르면 눌렸다고 토스트가 나오더라구요
근데 Disabled먹여서 시각적으로 비활성화 된 상태에서 LeftArrow버튼을 누르면 눌렸다고 토스트가 나와요!
![image](https://user-images.githubusercontent.com/20380647/182988145-ddd9bce7-3a34-4080-8716-983c99cc098a.png)
Disabled 키고 누른건데 토스트가 나와요...!

2022-08-05 02:25 UTC, chlwhdtn03 commented
맞는건가요?

2022-08-05 02:28 UTC, shlee4290 commented
아예 안눌리게 해주시면 좋을거 같네요

2022-08-05 02:34 UTC, islandparadise14 commented
if (isDisable) {
    return
}

2022-08-05 02:35 UTC, chlwhdtn03 commented
넵!
```kotlin
class TopBarButton : LinearLayout {
        var isDisabled = false
                set(value) {
                    field = value
                    setTopBarButtonInfo()
                    requestLayout()
                }
}
```

이 코드에서
```kotlin
class TopBarButton : LinearLayout {
        var isDisabled = false
                set(value) {
                    field = value
                    setTopBarButtonInfo()
                    requestLayout()
                    isEnabled = !isDisabled
                }
}
```
이렇게 고쳤습니다

2022-08-05 02:39 UTC, chlwhdtn03 commented
> if (isDisable) { return }

아 혹시 
```kotlin
class TopBarButton : LinearLayout {
        var isDisabled = false
                set(value) {
                    field = value
                    setTopBarButtonInfo()
                    requestLayout()
                    isEnabled = !isDisabled // 새로 넣은 부분
                }
}
```
이렇게 해도 괜찮을까요,,?
이미 커밋을..

2022-08-05 02:40 UTC, MintAOS commented
리뷰는 조언일뿐 구현방법은 구현자가 정하는거죠~

2022-08-05 02:44 UTC, chlwhdtn03 commented
아 YDS는 디자인만 맡는 부분이니까 YDS에서 클릭을 막거나 하는게 아닌거네요..! SoomSil에다가 저 코드를 넣고 isEnabled 수정한 코드는 돌려놓겠습니다 😭

2022-08-05 02:51 UTC, islandparadise14 commented
어… 글쎄요 디자인으로 인한 기능부니까 여기 들어가는게 맞지 않나요

2022-08-05 02:52 UTC, islandparadise14 commented
Disable 일때 클릭을 막는다 라는 기능을 숨쉴뿐 아니라 다른 여러 프로젝트에서 고려해야할 필요가 있을까요?

2022-08-05 02:53 UTC, chlwhdtn03 commented
아..! 그러네요 여기에 그대로 놔둬도 되겠네요

2022-08-05 02:58 UTC, chlwhdtn03 commented
말씀해주신 부분들 전부 고친듯 합니다!

2022-08-05 04:59 UTC, ByeongsuPark requested changes

2022-08-05 04:59 UTC, ByeongsuPark commented on DesignSystem/src/main/java/com/yourssu/design/system/component/SearchTopBar.kt
> +
backing field에 value 할당해주세요
이렇게 할 경우 서치탑바의 leftArrowDisabled 상태와 탑바버튼의 isDisabled 상태가 불일치하게 됩니다.
코틀린 바이트코드 디컴파일해서 자바 코드가 어떻게 구현되어 있는지 확인해보시면 좋을 것 같아요

2022-08-05 05:17 UTC, chlwhdtn03 commented on DesignSystem/src/main/java/com/yourssu/design/system/component/SearchTopBar.kt
> +
아! 까먹었어요 ㅠㅠㅠㅠ 바로 올리겠습니다

2022-08-05 05:48 UTC, ByeongsuPark approved these changes
👍

2022-08-05 07:33 UTC, chlwhdtn03 commented
머지해도 되나요!

2022-08-05 09:04 UTC, ByeongsuPark commented
넹 머지 가시져

2022-08-05 09:46 UTC, merged