SearchTopBar 구현
yourssu/YDS-Android pull request #59
Opened 2021-11-06 06:58 UTC by shlee4290

2021-11-06 14:04 UTC, ByeongsuPark submitted a review, later dismissed

2021-11-06 14:06 UTC, ByeongsuPark commented
피터님 스토리북 모듈 봤는데 SearchTextField에 아무 값이나 입력한 뒤에 isDisable를 true로 만들면 기존에 입력되어 있던 텍스트가 없어지는데 원래 명세가 그런건가요?

2021-11-06 16:06 UTC, shlee4290 commented
저거에 대한 명세가 없는거 같아서 저렇게 해놨었어요. 모든 textfield가 다 저럴거에요. 어떻게 할지 한번 확인해보는게 좋을거같네여

2021-11-06 16:10 UTC, shlee4290 commented
ios는 텍스트 유지되네요 ㅋㅋ 수정해야할듯

2021-11-07 07:50 UTC, islandparadise14 requested changes
@ByeongsuPark 본인이 의문이 있을때는 requestChange를 걸어버려요 ㅎㅎ

2021-11-07 07:54 UTC, islandparadise14 commented
플레이스 홀더 텍스트를 set 하는 부분이 있었으면 좋을것 같아요
그리고 가능하면 다른 화면들 보고 배경 변경되는 기능도 같이 추가하면 좋을것 같네요
<img width="589" alt="스크린샷 2021-11-07 오후 4 54 01" src="https://user-images.githubusercontent.com/39309953/140637054-7202f315-93c0-4045-9b1c-495629846849.png">
```
android:onClick="@{() -> viewModel.changeBackground()}"
android:background="@{viewModel.componentBackgroundColor}"
```
안내 텍스트는 덤으로?

2021-11-08 12:35 UTC, islandparadise14 approved these changes

2021-11-08 12:36 UTC, merged