[YDS-Tooltip] Tooltip 구현
yourssu/YDS-Android pull request #92
Opened 2022-04-30 04:56 UTC by rhthrhrl0

![image](https://user-images.githubusercontent.com/67176829/166091589-754f5ad6-1a3a-459e-a8ef-9ab3f6c20251.png)
일단 참조뷰에 대해서 원하는 위치에 띄우는 것과 화면 터치 시 종료되는 애니메이션까지 구현 완료했습니다.
문제는 툴팁을 띄운 상태에서 참조뷰가 이동하면 참조뷰가 못따라간다는 점입니다. 그래서 스토리북에서 다음과 같은 문제가 발생합니다.
![image](https://user-images.githubusercontent.com/67176829/166091672-ce60affb-4b36-42c8-b177-512ebd0679c8.png)
![image](https://user-images.githubusercontent.com/67176829/166091680-4fde9a23-b55b-418f-a641-da1240cbec41.png)

키보드를 올리고 텍스트 설명을 적는 동안 참조뷰가 위로 올라간 상태에서 툴팁을 띄우고 키보드를 내리면 툴팁은 그 자리에 고정되어서 남아있습니다.

2022-04-30 05:22 UTC, MintAOS commented
뭐 움직이는건 스펙에 없으니까
그냥 키보드 올라오거나 변화가 생길때 닫아버리죠

2022-04-30 05:23 UTC, MintAOS commented
변경점 스크롤 압박;; 천천히 볼게요

2022-04-30 09:07 UTC, islandparadise14 approved these changes
잘되네요 수고하셨어요~ 👍👍👍👍👍

2022-04-30 09:07 UTC, islandparadise14 commented on app/storybook/src/main/java/com/yourssu/storybook/atom/ToggleViewModel.kt
> +
불필요한 변경점

2022-04-30 09:07 UTC, islandparadise14 commented on DesignSystem/src/main/res/values/foundation_basic_colors.xml
> +
불필요한 변경점 2

2022-04-30 09:07 UTC, islandparadise14 commented on DesignSystem/src/main/java/com/yourssu/design/system/atom/ToolTip.kt
> +        }
Ctrl + Alt + L
or
Option + Command + L
써서 전체적으로 코드 정렬한번 하면 좋을것 같아요

2022-04-30 11:45 UTC, ByeongsuPark commented on DesignSystem/src/main/java/com/yourssu/design/system/atom/ToolTip.kt
> +                            animation.duration = 2500
duration 값이 2500이 맞나요?

2022-04-30 11:47 UTC, ByeongsuPark approved these changes

2022-04-30 11:47 UTC, ByeongsuPark commented on DesignSystem/src/main/java/com/yourssu/design/system/atom/ToolTip.kt
> +                            animation.duration = 2500
duration값이 2500이 맞나요?

2022-04-30 11:48 UTC, ByeongsuPark requested changes

2022-04-30 11:48 UTC, ByeongsuPark commented on DesignSystem/src/main/java/com/yourssu/design/system/atom/ToolTip.kt
> +                            animation.duration = 2500
요거 duration 2500이 맞나요?

2022-04-30 12:03 UTC, rhthrhrl0 commented on DesignSystem/src/main/java/com/yourssu/design/system/atom/ToolTip.kt
> +                            animation.duration = 2500
엇...... 그렇네요... 제가 이걸 왜 2500ms로 봤는지. 수정하겠습니다!

2022-04-30 12:04 UTC, islandparadise14 commented on DesignSystem/src/main/java/com/yourssu/design/system/atom/ToolTip.kt
> +                            animation.duration = 2500
올

2022-04-30 12:29 UTC, shlee4290 commented on DesignSystem/src/main/java/com/yourssu/design/system/atom/ToolTip.kt
> +            }
여기 이런 상황에서 IllegalStateException 던진건 매우 좋습니다 ㅎㅎ. 
근데 이런 필수인자들은 Builder 객체의 생성자로 전달받게 해서 꼭 넣어줘야만 Builder를 생성할 수 있게, Illegal State가 생기지 않도록 사전에 막는것도 좋을거같네여

2022-04-30 12:34 UTC, rhthrhrl0 commented on DesignSystem/src/main/java/com/yourssu/design/system/atom/ToolTip.kt
> +                            animation.duration = 2500
![image](https://user-images.githubusercontent.com/67176829/166105635-feed73ba-75d9-4cb6-8733-f35f749f1423.png)
아 여기서...  제가 short툴팁이랑 long툴팁은 1.5초 3초라서 미디엄툴팁을 2500ms로 잘못 본 거 같아요. 
그러면 short,medium,long툴팁 다 150ms , 250ms, 300ms 로 수정하겠습니다.

2022-04-30 12:35 UTC, shlee4290 commented on DesignSystem/src/main/java/com/yourssu/design/system/atom/ToolTip.kt
> +                } else if (true) {
여기 그냥 else로 안한 이유가 있나여

2022-04-30 12:37 UTC, shlee4290 commented on DesignSystem/src/main/java/com/yourssu/design/system/atom/ToolTip.kt
> +                3 -> {
요거 companion object에 방향 정의한 상수 있는거 같은데 그거로 바꾸는게 좋을거같아요

2022-04-30 12:42 UTC, shlee4290 commented on DesignSystem/src/main/java/com/yourssu/design/system/atom/ToolTip.kt
> +    private var Length: Float? = null
이런 변수 non-null이어야 더 안정적으로 쓸 수 있을거 같은데, null 대신 기본값 갖도록 수정해보면 어떨까여

2022-04-30 12:42 UTC, rhthrhrl0 commented on DesignSystem/src/main/java/com/yourssu/design/system/atom/ToolTip.kt
> +            }
오 생각해보니 그게 더 좋을 것 같네요! 수정하겠습니다

2022-04-30 12:44 UTC, rhthrhrl0 commented on DesignSystem/src/main/java/com/yourssu/design/system/atom/ToolTip.kt
> +                } else if (true) {
제가 안바꾼 것 같습니다. 애초에 저 조건문이 쓰일 일이 없을 것 같다고 단정 짓고 생각해서 제가 너무 대충 확인한 것 같네요.... 수정하겠습니다.

2022-04-30 12:44 UTC, rhthrhrl0 commented on DesignSystem/src/main/java/com/yourssu/design/system/atom/ToolTip.kt
> +                3 -> {
넵!

2022-04-30 12:48 UTC, rhthrhrl0 commented on DesignSystem/src/main/java/com/yourssu/design/system/atom/ToolTip.kt
> +                            animation.duration = 2500
다시보니 애초에 제가 저것도 툴팁 길이 별로 다르게 적용을 안했네요.

2022-04-30 12:49 UTC, rhthrhrl0 commented on DesignSystem/src/main/java/com/yourssu/design/system/atom/ToolTip.kt
> +    private var Length: Float? = null
넵 그렇게 하겠습니다.

2022-05-02 03:47 UTC, MintAOS commented
자동빌드 fail 이네요 한번 확인해주세요~

2022-05-02 06:54 UTC, rhthrhrl0 commented
> 자동빌드 fail 이네요 한번 확인해주세요~

conflict 해결하다가 ,를 빼먹었었네요... 수정했습니다!

2022-05-04 12:12 UTC, ByeongsuPark approved these changes

2022-05-04 12:12 UTC, merged